#!/bin/bash
# Teamwerk — Agent Team Launch
#
# Launches Claude Code with Agent Teams in a tmux session.
#
# Usage:
#   ./scripts/launch-team.sh                          # Use current directory
#   ./scripts/launch-team.sh /path/to/project         # Specify project path
#   ./scripts/launch-team.sh /path/to/project myname  # Custom session name
#   ./scripts/launch-team.sh --no-interactive          # Skip "Press Enter" prompt

set -euo pipefail

# --- Parse arguments ---
NO_INTERACTIVE=false
PROJECT_PATH=""
SESSION_NAME=""

for arg in "$@"; do
  case "$arg" in
    --no-interactive)
      NO_INTERACTIVE=true
      ;;
    *)
      if [ -z "$PROJECT_PATH" ]; then
        PROJECT_PATH="$arg"
      elif [ -z "$SESSION_NAME" ]; then
        SESSION_NAME="$arg"
      fi
      ;;
  esac
done

# Default project path: current directory
if [ -z "$PROJECT_PATH" ]; then
  PROJECT_PATH="$(pwd)"
fi

# Resolve to absolute path
PROJECT_PATH="$(cd "$PROJECT_PATH" 2>/dev/null && pwd)" || {
  echo "Error: Directory not found: $PROJECT_PATH"
  exit 1
}

# Default session name: project directory name (sanitized for tmux)
if [ -z "$SESSION_NAME" ]; then
  SESSION_NAME="$(basename "$PROJECT_PATH" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_-]/-/g')"
fi

# --- Preflight checks ---
command -v tmux >/dev/null 2>&1 || { echo "Error: tmux not installed. Run: brew install tmux (macOS) or apt install tmux (Linux)"; exit 1; }
command -v claude >/dev/null 2>&1 || { echo "Error: claude CLI not found"; exit 1; }

# Check if project is initialized
if [ ! -f "$PROJECT_PATH/docs/prd.md" ] && [ ! -f "$PROJECT_PATH/docs/acceptance-criteria.md" ]; then
  echo "Warning: Project not initialized. Run /init first to generate PRD and acceptance criteria."
  echo "Continuing anyway, but the Team Lead may not have enough context."
  echo ""
fi

echo "=== Teamwerk — Agent Team Launch ==="
echo ""
echo "Project:  $PROJECT_PATH"
echo "Session:  $SESSION_NAME"
echo ""
echo "The Team Lead will start automatically -- reading your PRD and kicking off the workflow."
echo "Attach to observe or interact at any time."
echo ""
echo "tmux cheatsheet:"
echo "  Detach (keep running):  Ctrl+B then D"
echo "  Reattach:               tmux attach -t $SESSION_NAME"
echo "  Kill:                   tmux kill-session -t $SESSION_NAME"
echo ""

if [ "$NO_INTERACTIVE" = false ] && [ -t 0 ]; then
  echo "Press Enter to launch..."
  read -r
fi

tmux kill-session -t "$SESSION_NAME" 2>/dev/null || true

# --- Create .teamwerk/ directory for progress tracking ---
mkdir -p "$PROJECT_PATH/.teamwerk"

# --- Git workflow preflight ---
# Reads teamwerk-config.yml to determine branching strategy, validates the current
# branch is not protected, and auto-creates a work branch if needed.
# NOTE: This is a simple grep-based parser, not a full YAML parser. It relies on
# the predictable structure of teamwerk-config.yml as generated by /init.

CONFIG_FILE="$PROJECT_PATH/teamwerk-config.yml"
GIT_STRATEGY="none"
GIT_CREATE_PR="false"
GIT_BRANCH_PREFIX="feature"
GIT_PR_TARGET=""
GIT_CONTEXT=""

if [ -f "$CONFIG_FILE" ] && [ -d "$PROJECT_PATH/.git" ]; then
  # Extract git strategy
  RAW_STRATEGY=$(grep -E '^\s+strategy:' "$CONFIG_FILE" 2>/dev/null | head -1 | sed 's/.*strategy:\s*//;s/["\x27 ]//g' || true)
  if [ -n "$RAW_STRATEGY" ]; then
    GIT_STRATEGY="$RAW_STRATEGY"
  fi

  # Extract create-pr value
  RAW_CREATE_PR=$(grep -E '^\s+create-pr:' "$CONFIG_FILE" 2>/dev/null | head -1 | sed 's/.*create-pr:\s*//;s/["\x27 ]//g' || true)
  if [ -n "$RAW_CREATE_PR" ]; then
    GIT_CREATE_PR="$RAW_CREATE_PR"
  fi

  # Extract branch-prefix
  RAW_PREFIX=$(grep -E '^\s+branch-prefix:' "$CONFIG_FILE" 2>/dev/null | head -1 | sed 's/.*branch-prefix:\s*//;s/["\x27 ]//g' || true)
  if [ -n "$RAW_PREFIX" ]; then
    GIT_BRANCH_PREFIX="$RAW_PREFIX"
  fi

  # Extract pr-target
  RAW_PR_TARGET=$(grep -E '^\s+pr-target:' "$CONFIG_FILE" 2>/dev/null | head -1 | sed 's/.*pr-target:\s*//;s/["\x27 ]//g' || true)
  if [ -n "$RAW_PR_TARGET" ]; then
    GIT_PR_TARGET="$RAW_PR_TARGET"
  fi

  # Resolve defaults based on strategy
  case "$GIT_STRATEGY" in
    github-flow|trunk-based)
      DEFAULT_PROTECTED="main"
      [ -z "$GIT_PR_TARGET" ] && GIT_PR_TARGET="main"
      [ "$RAW_CREATE_PR" = "" ] && GIT_CREATE_PR="true"
      ;;
    gitflow)
      DEFAULT_PROTECTED="main develop"
      [ -z "$GIT_PR_TARGET" ] && GIT_PR_TARGET="develop"
      [ "$RAW_CREATE_PR" = "" ] && GIT_CREATE_PR="true"
      ;;
    none|"")
      DEFAULT_PROTECTED=""
      GIT_STRATEGY="none"
      ;;
    *)
      echo "Warning: Unknown git strategy '$GIT_STRATEGY'. Treating as 'none'."
      GIT_STRATEGY="none"
      DEFAULT_PROTECTED=""
      ;;
  esac

  # Read explicit protected-branches from config, or use defaults
  PROTECTED_BRANCHES=""
  if [ "$GIT_STRATEGY" != "none" ]; then
    CUSTOM_PROTECTED=$(grep -A 10 'protected-branches:' "$CONFIG_FILE" 2>/dev/null | grep -E '^\s+- ' | sed 's/.*- //;s/["\x27 ]//g' | tr '\n' ' ' || true)
    if [ -n "$CUSTOM_PROTECTED" ]; then
      PROTECTED_BRANCHES="$CUSTOM_PROTECTED"
    else
      PROTECTED_BRANCHES="$DEFAULT_PROTECTED"
    fi
  fi

  # --- Branch validation and auto-creation ---
  if [ "$GIT_STRATEGY" != "none" ]; then
    cd "$PROJECT_PATH"
    CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")

    if [ -n "$CURRENT_BRANCH" ]; then
      IS_PROTECTED=false
      for pb in $PROTECTED_BRANCHES; do
        if [ "$CURRENT_BRANCH" = "$pb" ]; then
          IS_PROTECTED=true
          break
        fi
      done

      if [ "$IS_PROTECTED" = true ]; then
        TIMESTAMP=$(date +%Y%m%d-%H%M)
        NEW_BRANCH="${GIT_BRANCH_PREFIX}/${SESSION_NAME}-${TIMESTAMP}"

        # Handle rare same-minute collision
        if git rev-parse --verify "$NEW_BRANCH" >/dev/null 2>&1; then
          SUFFIX=$(head -c 4 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 4)
          NEW_BRANCH="${GIT_BRANCH_PREFIX}/${SESSION_NAME}-${TIMESTAMP}-${SUFFIX}"
        fi

        echo "Branch '$CURRENT_BRANCH' is protected ($GIT_STRATEGY strategy)."
        echo "Creating work branch: $NEW_BRANCH"
        echo ""

        git checkout -b "$NEW_BRANCH" || {
          echo "Error: Failed to create branch '$NEW_BRANCH'."
          echo "You may have uncommitted changes. Try: git stash  or  git commit -am 'WIP'"
          exit 1
        }
      fi
    fi

    # Check gh CLI if PR creation is enabled
    if [ "$GIT_CREATE_PR" = "true" ]; then
      if ! command -v gh >/dev/null 2>&1; then
        echo "Warning: 'gh' CLI not found. Team Lead cannot create draft PRs."
        echo "Install: brew install gh (macOS) or https://cli.github.com/"
        echo ""
      fi
    fi

    # Build git context for the Team Lead prompt
    WORK_BRANCH=$(cd "$PROJECT_PATH" && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
    GIT_CONTEXT="GIT CONTEXT: Working on branch ${WORK_BRANCH}. Strategy is ${GIT_STRATEGY}. Protected branches: ${PROTECTED_BRANCHES}."
    if [ "$GIT_CREATE_PR" = "true" ]; then
      GIT_CONTEXT="${GIT_CONTEXT} When ALL work is complete, create a draft PR targeting ${GIT_PR_TARGET} and report the URL."
    fi

    echo "Git:      $GIT_STRATEGY (branch: $WORK_BRANCH, PR target: $GIT_PR_TARGET)"
    echo ""
  fi
fi

# --- Team Lead auto-start prompt ---
# The claude CLI accepts a positional prompt and --append-system-prompt.
# We use both so the Team Lead reads context and presents the launch menu.
# NOTE: Prompt strings must not contain double quotes, backslashes, or dollar signs.
TEAM_SYSTEM="You are the Team Lead for a Teamwerk agent team. Use the team-lead skill for your full role definition and workflow. You coordinate the team -- you do not write implementation code yourself. Do NOT explore the codebase or launch research agents. Read the config to discover where work items live. ${GIT_CONTEXT} COMPACT INSTRUCTIONS: When compacting, ALWAYS preserve: the full team roster (which teammates exist and their roles, including Test Designer and Adversarial Reviewer), all task assignments and their current status, which acceptance criteria are active vs archived, the launch menu selection the user made, current phase of work, the current git branch and PR target, and any blockers or dependencies between teammates. After compaction, re-read .teamwerk/team-state.md to restore coordination state."

TEAM_PROMPT="Use the team-lead skill. Read ONLY these files: teamwerk-config.yml, docs/prd.md, CLAUDE.md. Check if .teamwerk/team-state.md exists. Then present the launch menu and wait for the user to choose before taking action. Do NOT start building or spawning teammates until the user has selected an option."

tmux new-session -d -s "$SESSION_NAME" -c "$PROJECT_PATH" \
  "unset CLAUDECODE && export CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1 && claude --dangerously-skip-permissions --append-system-prompt \"$TEAM_SYSTEM\" \"$TEAM_PROMPT\""

# --- Verify session started ---
# Give claude a moment to initialize, then check the session is alive.
# If claude exits immediately (API error, auth failure, etc.), tmux destroys
# the session and the user gets a cryptic non-zero exit code with no message.
sleep 1
if ! tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
  echo ""
  echo "Error: Session '$SESSION_NAME' died immediately after creation."
  echo "The claude CLI may have failed to start. Common causes:"
  echo "  - No internet connection (Claude needs API access)"
  echo "  - Authentication expired (run 'claude' alone to re-auth)"
  echo "  - Another claude session is blocking"
  echo ""
  echo "To debug, try running claude manually:"
  echo "  cd $PROJECT_PATH && claude"
  exit 1
fi

# --- Attach or report ---
# Disable errexit for the attach — tmux attach returns non-zero both on error
# AND on normal detach (Ctrl+B D), so we handle it explicitly.
set +e
if [ -t 0 ] && [ -t 1 ]; then
  tmux attach-session -t "$SESSION_NAME"
  ATTACH_EXIT=$?
  if [ $ATTACH_EXIT -ne 0 ]; then
    if tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
      echo ""
      echo "Detached from session '$SESSION_NAME' (still running)."
      echo "Reattach: tmux attach -t $SESSION_NAME"
    else
      echo ""
      echo "Error: Session '$SESSION_NAME' exited unexpectedly."
      echo "The claude CLI may have crashed. To debug, try:"
      echo "  cd $PROJECT_PATH && claude"
    fi
  fi
else
  echo "✅ tmux session '$SESSION_NAME' is running. Team Lead is starting automatically."
  echo ""
  echo "To observe progress, open a terminal and run:"
  echo "  tmux attach -t $SESSION_NAME"
fi
